-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 14, 2020 at 06:15 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.2.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sports`
--

-- --------------------------------------------------------

--
-- Table structure for table `sign_up`
--

CREATE TABLE `sign_up` (
  `sr no` int(11) NOT NULL,
  `username` varchar(30) NOT NULL,
  `email id` varchar(30) NOT NULL,
  `password` varchar(30) NOT NULL,
  `datetime` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `sign_up`
--

INSERT INTO `sign_up` (`sr no`, `username`, `email id`, `password`, `datetime`) VALUES
(1, 'abcde', 'abc@gmail.com', '111', '2020-08-14 15:39:45'),
(18, 'prasad', '', '', '2020-08-14 16:12:50'),
(21, 'bhargavi', 'abc@gmail.com', '111', '2020-08-14 17:18:31'),
(25, 'prasad1', 'abc@gmail.com', '111', '2020-08-14 17:34:32');

-- --------------------------------------------------------

--
-- Table structure for table `sports`
--

CREATE TABLE `sports` (
  `sport_id` int(11) NOT NULL,
  `sport_name` varchar(30) NOT NULL,
  `sport_desc` text NOT NULL,
  `days` text NOT NULL,
  `timing` varchar(20) NOT NULL,
  `sport_fee` int(10) NOT NULL,
  `Quotes` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `sports`
--

INSERT INTO `sports` (`sport_id`, `sport_name`, `sport_desc`, `days`, `timing`, `sport_fee`, `Quotes`) VALUES
(1, 'Cricket', 'Cricket is a bat-and-ball game played between two teams of eleven players on a field at the centre of which is a 20-metre (22-yard) pitch with a wicket at each end, each comprising two bails balanced on three stumps. The batting side scores runs by striking the ball bowled at the wicket with the bat, while the bowling and fielding side tries to prevent this and dismiss each batter (so they are \"out\"). Means of dismissal include being bowled, when the ball hits the stumps and dislodges the bails, and by the fielding side catching the ball after it is hit by the bat, but before it hits the ground. When ten batters have been dismissed, the innings ends and the teams swap roles. The game is adjudicated by two umpires, aided by a third umpire and match referee in international matches. They communicate with two off-field scorers who record the match\'s statistical information.\r\n\r\nForms of cricket range from Twenty20, with each team batting for a single innings of 20 overs, to Test matches played over five days. Traditionally cricketers play in all-white kit, but in limited overs cricket they wear club or team colours. In addition to the basic kit, some players wear protective gear to prevent injury caused by the ball, which is a hard, solid spheroid made of compressed leather with a slightly raised sewn seam enclosing a cork core layered with tightly wound string.\r\n\r\nThe earliest reference to cricket is in South East England in the mid-16th century. It spread globally with the expansion of the British Empire, with the first international matches in the second half of the 19th century. The game\'s governing body is the International Cricket Council (ICC), which has over 100 members, twelve of which are full members who play Test matches. The game\'s rules, the Laws of Cricket, are maintained by Marylebone Cricket Club (MCC) in London. The sport is followed primarily in the Indian subcontinent, Australasia, the United Kingdom, southern Africa and the West Indies.[1] Women\'s cricket, which is organised and played separately, has also achieved international standard. The most successful side playing international cricket is Australia, which has won seven One Day International trophies, including five World Cups, more than any other country and has been the top-rated Test side more than any other country.', 'Sunday, Tuesday, Thursday', '07:00 am-10:00 am', 12000, ' “People throw stones at you and you convert them into milestones.” – Sachin Tendulkar'),
(2, 'Football', 'Football is a family of team sports that involve, to varying degrees, kicking a ball to score a goal. Unqualified, the word football normally means the form of football that is the most popular where the word is used. Sports commonly called football include association football (known as soccer in some countries); gridiron football (specifically American football or Canadian football); Australian rules football; rugby football (either rugby union or rugby league); and Gaelic football.[1][2] These various forms of football share to varying extent common origins and are known as football codes.\r\n\r\nThere are a number of references to traditional, ancient, or prehistoric ball games played in many different parts of the world.[3][4][5] Contemporary codes of football can be traced back to the codification of these games at English public schools during the 19th century.[6][7] The expansion of the British Empire allowed these rules of football to spread to areas of British influence outside the directly controlled Empire.[8] By the end of the 19th century, distinct regional codes were already developing: Gaelic football, for example, deliberately incorporated the rules of local traditional football games in order to maintain their heritage.[9] In 1888, The Football League was founded in England, becoming the first of many professional football competitions. During the 20th century, several of the various kinds of football grew to become some of the most popular team sports in the world.[10]\r\n\r\n\r\n', 'Sunday, Tuesday, Thursday', '07:00am-10:00am', 8999, 'When you win, you don\'t get carries away. but if you go step by step, with confidence, you can go far - Diego Maradona'),
(3, 'Swimming', 'Swimming is the self-propulsion of a person through water, usually for recreation, sport, exercise, or survival. Locomotion is achieved through coordinated movement of the limbs, the body, or both. Humans can hold their breath underwater and undertake rudimentary locomotive swimming within weeks of birth, as a survival response.[1]\r\n\r\nSwimming is consistently among the top public recreational activities,[2][3][4][5] and in some countries, swimming lessons are a compulsory part of the educational curriculum.[6] As a formalized sport, swimming features in a range of local, national, and international competitions, including every modern Summer Olympics.Swimming is the self-propulsion of a person through water, usually for recreation, sport, exercise, or survival. Locomotion is achieved through coordinated movement of the limbs, the body, or both. Humans can hold their breath underwater and undertake rudimentary locomotive swimming within weeks of birth, as a survival response.[1]\r\n\r\nSwimming is consistently among the top public recreational activities,[2][3][4][5] and in some countries, swimming lessons are a compulsory part of the educational curriculum.[6] As a formalized sport, swimming features in a range of local, national, and international competitions, including every modern Summer Olympics.', 'Sunday, Tuesday, Wednesday', '12:00pm-02:00pm', 3500, '“The man who is swimming against the stream knows the strength of it”-. Woodrow Wilson'),
(4, 'Badminton', 'Badminton is a racquet sport played using racquets to hit a shuttlecock across a net. Although it may be played with larger teams, the most common forms of the game are \"singles\" (with one player per side) and \"doubles\" (with two players per side). Badminton is often played as a casual outdoor activity in a yard or on a beach; formal games are played on a rectangular indoor court. Points are scored by striking the shuttlecock with the racquet and landing it within the opposing side\'s half of the court.\r\n\r\nEach side may only strike the shuttlecock once before it passes over the net. Play ends once the shuttlecock has struck the floor or if a fault has been called by the umpire, service judge, or (in their absence) the opposing side.[1]\r\n\r\nThe shuttlecock is a feathered or (in informal matches) plastic projectile which flies differently from the balls used in many other sports. In particular, the feathers create much higher drag, causing the shuttlecock to decelerate more rapidly. Shuttlecocks also have a high top speed compared to the balls in other racquet sports. The flight of the shuttlecock gives the sport its distinctive nature.\r\n\r\nThe game developed in British India from the earlier game of battledore and shuttlecock. European play came to be dominated by Denmark but the game has become very popular in Asia, with recent competitions dominated by China. Since 1992, badminton has been a Summer Olympic sport with four events: men\'s singles, women\'s singles, men\'s doubles, and women\'s doubles,[2] with mixed doubles added four years later. At high levels of play, the sport demands excellent fitness: players require aerobic stamina, agility, strength, speed, and precision. It is also a technical sport, requiring good motor coordination and the development of sophisticated racquet movements.', 'Sunday,Monday,Tuesday', '04:00pm-06:00pm', 3000, '“Those who play badminton well take decisions quickly”-Dmitry Medvedev:'),
(6, 'Basket ball', 'Basketball is a team sport in which two teams, most commonly of five players each, opposing one another on a rectangular court, compete with the primary objective of shooting a basketball (approximately 9.4 inches (24 cm) in diameter) through the defender\'s hoop (a basket 18 inches (46 cm) in diameter mounted 10 feet (3.048 m) high to a backboard at each end of the court) while preventing the opposing team from shooting through their own hoop. A field goal is worth two points, unless made from behind the three-point line, when it is worth three. After a foul, timed play stops and the player fouled or designated to shoot a technical foul is given one or more one-point free throws. The team with the most points at the end of the game wins, but if regulation play expires with the score tied, an additional period of play (overtime) is mandated.\r\n\r\nPlayers advance the ball by bouncing it while walking or running (dribbling) or by passing it to a teammate, both of which require considerable skill. On offense, players may use a variety of shots—the lay-up, the jump shot, or a dunk; on defense, they may steal the ball from a dribbler, intercept passes, or block shots; either offense or defense may collect a rebound, that is, a missed shot that bounces from rim or backboard. It is a violation to lift or drag one\'s pivot foot without dribbling the ball, to carry it, or to hold the ball with both hands then resume dribbling.\r\n\r\nThe five players on each side fall into five playing positions. The tallest player is usually the center, the second tallest and strongest is the power forward, a slightly shorter but more agile player is the small forward, and the shortest players or the best ball handlers are the shooting guard and the point guard, who implements the coach\'s game plan by\r\n\r\n', 'Sunday, Tuesday, Friday', '08:00am-11:00am', 5500, '“Talent wins games, but teamwork and intelligence win championships.” Michael Jordan'),
(8, 'Boxing', 'Boxing is a combat sport in which two people, usually wearing protective gloves, throw punches at each other for a predetermined amount of time in a boxing ring.\r\n\r\nAmateur boxing is both an Olympic and Commonwealth Games sport and is a standard fixture in most international games—it also has its own World Championships. Boxing is overseen by a referee over a series of one- to three-minute intervals called rounds.\r\n\r\nA winner can be resolved before the completion of the rounds when a referee deems an opponent incapable of continuing, disqualification of an opponent, or resignation of an opponent. When the fight reaches the end of its final round with both opponents still standing, the judges\' scorecards determine the victor. In the event that both fighters gain equal scores from the judges, professional bouts are considered a draw. In Olympic boxing, because a winner must be declared, judges award the contest to one fighter on technical criteria.\r\n\r\nWhile humans have fought in hand-to-hand combat since the dawn of human history, the earliest evidence of fist-fighting sporting contests date back to the ancient Near East in the 3rd and 2nd millennia BC.[2] The earliest evidence of boxing rules date back to Ancient Greece, where boxing was established as an Olympic game in 688 BC.[2] Boxing evolved from 16th- and 18th-century prizefights, largely in Great Britain, to the forerunner of modern boxing in the mid-19th century with the 1867 introduction of the Marquess of Queensberry Rules.\r\n\r\n\r\n', 'Sunday,Monday,Tuesday', '08:00pm-10:00pm', 5000, '“NEVER A VICTIM, FOREVER A FIGHTER”'),
(9, 'Karate', 'Karate (空手) (/kəˈrɑːti/; Japanese pronunciation: [kaɾate] (About this soundlisten); Okinawan pronunciation: [kaɽati]) is a martial art developed in the Ryukyu Kingdom. It developed from the indigenous Ryukyuan martial arts (called te (手), \"hand\"; tii in Okinawan) under the influence of Kung Fu, particularly Fujian White Crane.[1][2] Karate is now predominantly a striking art using punching, kicking, knee strikes, elbow strikes and open-hand techniques such as knife-hands, spear-hands and palm-heel strikes. Historically, and in some modern styles, grappling, throws, joint locks, restraints and vital-point strikes are also taught.[3] A karate practitioner is called a karateka (空手家), and its plural is \"karateka\" or \"karatekas\".\r\n\r\nThe Empire of Japan annexed the Ryukyu Kingdom in 1879. Karate came to the Japanese archipelago in the early 20th century during a time of migration as Ryukyuans, especially from Okinawa, looked for work in Japan.[4] It was systematically taught in Japan after the Taishō era of 1912–1926.[5] In 1922 the Japanese Ministry of Education invited Gichin Funakoshi to Tokyo to give a karate demonstration. In 1924 Keio University established the first university karate club in mainland Japan, and by 1932 major Japanese universities had karate clubs.[6] In this era of escalating Japanese militarism,[7] the name was changed from 唐手 (\"Chinese hand\" or \"Tang hand\")[8] to 空手 (\"empty hand\") – both of which are pronounced karate in Japanese – to indicate that the Japanese wished to develop the combat form in Japanese style.[9] After World War II, Okinawa became (1945) an important United States military site and karate became popular among servicemen stationed there.[10]\r\n\r\nThe martial-arts movies of the 1960s and 1970s served to greatly increase the popularity of martial arts around the world, and English-speakers began to use the word karate in a generic way to refer to all striking-based Asian martial arts.[11] Karate schools began appearing across the world, catering to those with casual interest as well as those seeking a deeper study of the art.\r\n\r\nShigeru E', 'Wednesday,Friday,Sunday', '06:00pm-08:00pm', 9000, 'Lorem ipsu redominantly a striking art using punching, kickingm doloa'),
(14, 'Hockey', 'Hockey is a sport in which two teams play against each other by trying to manoeuvre a ball or a puck into the opponent\'s goal using a hockey stick. There are many types of hockey such as bandy, field hockey, ice hockey and rink hockey.\r\n\r\nIn most of the world, the term hockey by itself refers to field hockey, while in Canada, the United States, Russia and most of Eastern and Northern Europe, the term usually refers to ice hockey.Games played with curved sticks and a ball can be found in the histories of many cultures. In Egypt, 4000-year-old carvings feature teams with sticks and a projectile, hurling dates to before 1272 BC in Ireland, and there is a depiction from approximately 600 BC in Ancient Greece, where the game may have been called kerētízein or (κερητίζειν) because it was played with a horn or horn-like stick (kéras, κέρας).[10] In Inner Mongolia, the Daur people have been playing beikou, a game similar to modern field hockey, for about 1,000 yearsGames played with curved sticks and a ball can be found in the histories of many cultures. In Egypt, 4000-year-old carvings feature teams with sticks and a projectile, hurling dates to before 1272 BC in Ireland, and there is a depiction from approximately 600 BC in Ancient Greece, where the game may have been called kerētízein or (κερητίζειν) because it was played with a horn or horn-like stick (kéras, κέρας).[10] In Inner Mongolia, the Daur people have been playing beikou, a game similar to modern field hockey, for about 1,000 years', 'Sunday, Tuesday,Friday', '07:00am-10:00am', 7500, 'A good player plays where the ball is. A great player plays where the ball is going to be.'),
(15, 'Tennis', 'Tennis is a racket sport that can be played individually against a single opponent (singles) or between two teams of two players each (doubles). Each player uses a tennis racket that is strung with cord to strike a hollow rubber ball covered with felt over or around a net and into the opponent\'s court. The object of the game is to maneuver the ball in such a way that the opponent is not able to play a valid return. The player who is unable to return the ball will not gain a point, while the opposite player will.\r\n\r\nTennis is an Olympic sport and is played at all levels of society and at all ages. The sport can be played by anyone who can hold a racket, including wheelchair users. The modern game of tennis originated in Birmingham, England, in the late 19th century as lawn tennis.[1] It had close connections both to various field (lawn) games such as croquet and bowls as well as to the older racket sport today called real tennis. During most of the 19th century, in fact, the term tennis referred to real tennis, not lawn tennis.\r\n\r\nThe rules of modern tennis have changed little since the 1890s. Two exceptions are that from 1908 to 1961 the server had to keep one foot on the ground at all times, and the adoption of the tiebreak in the 1970s. A recent addition to professional tennis has been the adoption of electronic review technology coupled with a point-challenge system, which allows a player to contest the line call of a point, a system known as Hawk-Eye.\r\n\r\nTennis is played by millions of recreational players and is also a popular worldwide spectator sport. The four Grand Slam tournaments (also referred to as the Majors) are especially popular: the Australian Open played on hard courts, the French Open played on red clay courts, Wimbledon played on grass courts, and the US Open also played on hard courts.\r\n\r\n\r\n', 'Wednesday, Friday, Sunday', '10:00am-12:00pm', 6000, 'If you can keep playing tennis when somebody is shooting a gun down the street, that’s concentration. ―Serena Williams'),
(16, 'Chess', 'Chess is a two-player strategy board game played on a checkered board with 64 squares arranged in an 8×8 square grid. Played by millions of people worldwide, chess is believed to be derived from the Indian game chaturanga sometime before the 7th century. Chaturanga is also the likely ancestor of the East Asian strategy games xiangqi (Chinese chess), janggi (Korean chess), and shogi (Japanese chess). Chess reached Europe via Persia and Arabia by the 9th century, due to the Umayyad conquest of Hispania. The pieces assumed their current properties in Spain in the late 15th century, and the modern rules were standardized in the 19th century.\r\n\r\nPlay involves no hidden information. Each player begins with 16 pieces: one king, one queen, two rooks, two knights, two bishops, and eight pawns. Each piece type moves differently, with the most powerful being the queen and the least powerful the pawn. The objective is to checkmate the opponent\'s king by placing it under an inescapable threat of capture. To this end, a player\'s pieces are used to attack and capture the opponent\'s pieces, while supporting one another. During the game, play typically involves exchanging pieces for the opponent\'s similar pieces, and finding and engineering opportunities to trade advantageously or to get a better position. In addition to checkmate, a player wins the game if the opponent resigns, or, in a timed game, runs out of time. There are also several ways that a game can end in a draw.\r\n\r\nThe first generally recognized World Chess Champion, Wilhelm Steinitz, claimed his title in 1886. Since 1948, the World Championship has been regulated by the Fédération Internationale des Échecs (FIDE), the game\'s international governing body. FIDE also awards life-time master titles to skilled players, the highest of which is Grandmaster (GM). Many national chess organizations have a title system of their own. FIDE also organizes the Women\'s World Championship, the World Junior Championship, the World Senior Championship, the Blitz and Rapid World Championships, the Chess World Cup, and the Chess Olympiad, a popular competition among international teams. FIDE is a member of the International Olympic Committee, which can be considered recognition of chess as a sport.[1] Several national sporting bodies (e.g. the Spanish Consejo Superior de Deportes[2]) also recognize chess as a sport. Chess was included in the 2006 and 2010 Asian Games. There is also a Correspondence Chess World Championship and a World Computer Chess Championship. Online chess has opened amateur and professional competition to a wide and varied group of players.', 'Thursday, Friday, Saturday', '08:00 am - 10:00 am', 9000, '“Chess is the gymnasium of the mind.” – Blaise Pascal'),
(17, 'Martial arts', 'Martial arts can also be linked with religion and spirituality. Numerous systems are reputed to have been founded, disseminated, or practiced by monks or nuns.\r\n\r\nThroughout the Asian arts, meditation may be incorporated as a part of training. In the arts influenced by Hindu-Buddhist philosophy, the practice itself may be used as an aid to attaining enlightenment.\r\n\r\nJapanese styles, when concerning non-physical qualities of the combat, are often strongly influenced by Mahayana Buddhist philosophy. Concepts like \"empty mind\" and \"beginner\'s mind\" are recurrent. Aikido practitioners for instance, can have a strong philosophical belief of the flow of energy and peace fostering, as idealised by the art\'s founder Morihei Ueshiba.\r\n\r\nTraditional Korean martial arts place emphasis on the development of the practitioner\'s spiritual and philosophical development. A common theme in most Korean styles, such as Taekkyon and taekwondo, is the value of \"inner peace\" in a practitioner, which is stressed to be only achievable through individual meditation and training. The Koreans believe that the use of physical force is only justifiable for self defense.[citation needed]\r\n\r\nSystema draws upon breathing and relaxation techniques, as well as elements of Russian Orthodox thought, to foster self-conscience and calmness, and to benefit the practitioner in different levels: the physical, the psychological and the spiritual.[5]\r\n\r\nSome martial arts in various cultures can be performed in dance-like settings for various reasons, such as for evoking ferocity in preparation for battle or showing off skill in a more stylized manner, with capoeira being the most prominent example. Many such martial arts incorporate music, especially strong percussive rhythms. (See also war dance.)\r\n\r\n', 'Monday, Wednesday, Friday', '07:30 pm - 09:30 pm', 11000, '“It does not matter how slowly you go as long as you do not stop” - Confucius'),
(18, 'Volleyball', 'Volleyball is a team sport in which two teams of six players are separated by a net. Each team tries to score points by grounding a ball on the other team\'s court under organized rules.[1] It has been a part of the official program of the Summer Olympic Games since Tokyo 1964.\r\n\r\nThe complete set of rules is extensive,[2] but play essentially proceeds as follows: a player on one of the teams begins a \'rally\' by serving the ball (tossing or releasing it and then hitting it with a hand or arm), from behind the back boundary line of the court, over the net, and into the receiving team\'s court.[3] The receiving team must not let the ball be grounded within their court. The team may touch the ball up to 3 times, but individual players may not touch the ball twice consecutively.[3] Typically, the first two touches are used to set up for an attack, an attempt to direct the ball back over the net in such a way that the serving team is unable to prevent it from being grounded in their court.\r\n\r\nThe rally continues, with each team allowed as many as three consecutive touches, until either (1): a team makes a kill, grounding the ball on the opponent\'s court and winning the rally; or (2): a team commits a fault and loses the rally. The team that wins the rally is awarded a point and serves the ball to start the next rally. A few of the most common faults include:\r\n\r\ncausing the ball to touch the ground or floor outside the opponents\' court or without first passing over the net;\r\ncatching and throwing the ball;\r\ndouble hit: two consecutive contacts with the ball made by the same player;\r\nfour consecutive contacts with the ball made by the same team;\r\nnet foul: touching the net during play;\r\nfoot fault: the foot crosses over the boundary line when serving.\r\nThe ball is usually played with the hands or arms, but players can legally strike or push (short contact) the ball with any part of the body.', 'Tuesday, Thursday, Saturday', '09:00 am - 11:00 am', 6500, '\"There\'s nothing worse than the feeling of wishing you had another chance at a play because you weren\'t ready\"');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `sign_up`
--
ALTER TABLE `sign_up`
  ADD PRIMARY KEY (`sr no`),
  ADD UNIQUE KEY `username` (`username`);

--
-- Indexes for table `sports`
--
ALTER TABLE `sports`
  ADD PRIMARY KEY (`sport_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `sign_up`
--
ALTER TABLE `sign_up`
  MODIFY `sr no` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- AUTO_INCREMENT for table `sports`
--
ALTER TABLE `sports`
  MODIFY `sport_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
